---
kind: auto.CommandConfig
name: snapshot-decoder
spec:
  disableImage: true
---
kind: common.Image
name: image-discovery-service
spec:
    extraEnvironment:
      PLATFORM: linux/amd64,linux/arm64
---
kind: golang.Build
spec:
  outputs:
    linux-amd64:
      GOOS: linux
      GOARCH: amd64
    linux-arm64:
      GOOS: linux
      GOARCH: arm64
---
kind: golang.Generate
spec:
  baseSpecPath: /api
  vtProtobufEnabled: true
  specs:
    - source: api/storage/discovery.proto
      subdirectory: storage
      genGateway: false
---
kind: service.CodeCov
spec:
  targetThreshold: 30
---
kind: common.Repository
spec:
  licenses:
    - enabled: true
      id: BSL-1.1
      params:
        Licensor: Sidero Labs, Inc.
        LicensedWork: Discovery Service
        Copyright: (c) 2024 Sidero Labs, Inc.
        ChangeDate: "2029-07-03"
        ChangeLicense: Mozilla Public License, version 2.0
        EnterpriseLink: https://www.siderolabs.com/contact/
      header: |
        // Copyright (c) 2024 Sidero Labs, Inc.
        //
        // Use of this software is governed by the Business Source License
        // included in the LICENSE file.
---
kind: golang.UnitTests
spec:
  runFIPS: true
