// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: storage/discovery.proto

package storagepb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StateSnapshot is the snapshot of the discovery service state.
type StateSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clusters      []*ClusterSnapshot     `protobuf:"bytes,1,rep,name=clusters,proto3" json:"clusters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateSnapshot) Reset() {
	*x = StateSnapshot{}
	mi := &file_storage_discovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateSnapshot) ProtoMessage() {}

func (x *StateSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_storage_discovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateSnapshot.ProtoReflect.Descriptor instead.
func (*StateSnapshot) Descriptor() ([]byte, []int) {
	return file_storage_discovery_proto_rawDescGZIP(), []int{0}
}

func (x *StateSnapshot) GetClusters() []*ClusterSnapshot {
	if x != nil {
		return x.Clusters
	}
	return nil
}

// ClusterSnapshot is the snapshot of a cluster with a set of affiliates.
type ClusterSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Affiliates    []*AffiliateSnapshot   `protobuf:"bytes,2,rep,name=affiliates,proto3" json:"affiliates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterSnapshot) Reset() {
	*x = ClusterSnapshot{}
	mi := &file_storage_discovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterSnapshot) ProtoMessage() {}

func (x *ClusterSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_storage_discovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterSnapshot.ProtoReflect.Descriptor instead.
func (*ClusterSnapshot) Descriptor() ([]byte, []int) {
	return file_storage_discovery_proto_rawDescGZIP(), []int{1}
}

func (x *ClusterSnapshot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClusterSnapshot) GetAffiliates() []*AffiliateSnapshot {
	if x != nil {
		return x.Affiliates
	}
	return nil
}

// AffiliateSnapshot is the snapshot of an affiliate that is part of a cluster with a set of endpoints.
type AffiliateSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Expiration    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expiration,proto3" json:"expiration,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Endpoints     []*EndpointSnapshot    `protobuf:"bytes,4,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AffiliateSnapshot) Reset() {
	*x = AffiliateSnapshot{}
	mi := &file_storage_discovery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AffiliateSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AffiliateSnapshot) ProtoMessage() {}

func (x *AffiliateSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_storage_discovery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AffiliateSnapshot.ProtoReflect.Descriptor instead.
func (*AffiliateSnapshot) Descriptor() ([]byte, []int) {
	return file_storage_discovery_proto_rawDescGZIP(), []int{2}
}

func (x *AffiliateSnapshot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AffiliateSnapshot) GetExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

func (x *AffiliateSnapshot) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AffiliateSnapshot) GetEndpoints() []*EndpointSnapshot {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

// EndpointSnapshot is the snapshot of an endpoint of an affiliate.
type EndpointSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expiration    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=expiration,proto3" json:"expiration,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointSnapshot) Reset() {
	*x = EndpointSnapshot{}
	mi := &file_storage_discovery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointSnapshot) ProtoMessage() {}

func (x *EndpointSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_storage_discovery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointSnapshot.ProtoReflect.Descriptor instead.
func (*EndpointSnapshot) Descriptor() ([]byte, []int) {
	return file_storage_discovery_proto_rawDescGZIP(), []int{3}
}

func (x *EndpointSnapshot) GetExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

func (x *EndpointSnapshot) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_storage_discovery_proto protoreflect.FileDescriptor

const file_storage_discovery_proto_rawDesc = "" +
	"\n" +
	"\x17storage/discovery.proto\x12\x18sidero.discovery.storage\x1a\x1fgoogle/protobuf/timestamp.proto\"V\n" +
	"\rStateSnapshot\x12E\n" +
	"\bclusters\x18\x01 \x03(\v2).sidero.discovery.storage.ClusterSnapshotR\bclusters\"n\n" +
	"\x0fClusterSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12K\n" +
	"\n" +
	"affiliates\x18\x02 \x03(\v2+.sidero.discovery.storage.AffiliateSnapshotR\n" +
	"affiliates\"\xbd\x01\n" +
	"\x11AffiliateSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12:\n" +
	"\n" +
	"expiration\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiration\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12H\n" +
	"\tendpoints\x18\x04 \x03(\v2*.sidero.discovery.storage.EndpointSnapshotR\tendpoints\"b\n" +
	"\x10EndpointSnapshot\x12:\n" +
	"\n" +
	"expiration\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiration\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04dataB7Z5github.com/siderolabs/discovery-service/api/storagepbb\x06proto3"

var (
	file_storage_discovery_proto_rawDescOnce sync.Once
	file_storage_discovery_proto_rawDescData []byte
)

func file_storage_discovery_proto_rawDescGZIP() []byte {
	file_storage_discovery_proto_rawDescOnce.Do(func() {
		file_storage_discovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_discovery_proto_rawDesc), len(file_storage_discovery_proto_rawDesc)))
	})
	return file_storage_discovery_proto_rawDescData
}

var file_storage_discovery_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_storage_discovery_proto_goTypes = []any{
	(*StateSnapshot)(nil),         // 0: sidero.discovery.storage.StateSnapshot
	(*ClusterSnapshot)(nil),       // 1: sidero.discovery.storage.ClusterSnapshot
	(*AffiliateSnapshot)(nil),     // 2: sidero.discovery.storage.AffiliateSnapshot
	(*EndpointSnapshot)(nil),      // 3: sidero.discovery.storage.EndpointSnapshot
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_storage_discovery_proto_depIdxs = []int32{
	1, // 0: sidero.discovery.storage.StateSnapshot.clusters:type_name -> sidero.discovery.storage.ClusterSnapshot
	2, // 1: sidero.discovery.storage.ClusterSnapshot.affiliates:type_name -> sidero.discovery.storage.AffiliateSnapshot
	4, // 2: sidero.discovery.storage.AffiliateSnapshot.expiration:type_name -> google.protobuf.Timestamp
	3, // 3: sidero.discovery.storage.AffiliateSnapshot.endpoints:type_name -> sidero.discovery.storage.EndpointSnapshot
	4, // 4: sidero.discovery.storage.EndpointSnapshot.expiration:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_storage_discovery_proto_init() }
func file_storage_discovery_proto_init() {
	if File_storage_discovery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_discovery_proto_rawDesc), len(file_storage_discovery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_storage_discovery_proto_goTypes,
		DependencyIndexes: file_storage_discovery_proto_depIdxs,
		MessageInfos:      file_storage_discovery_proto_msgTypes,
	}.Build()
	File_storage_discovery_proto = out.File
	file_storage_discovery_proto_goTypes = nil
	file_storage_discovery_proto_depIdxs = nil
}
