apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
images:
  - name: ghcr.io/siderolabs/discovery-service
    newName: ghcr.io/siderolabs/discovery-service
    newTag: v1.0.15
